version: '3.9'

networks:
  kafka-net:
    name: kafka-net

volumes:
  vol_kafka0_data:
    name: vol_kafka0_data
  vol_kafka1_data:
    name: vol_kafka1_data
  vol_kafka2_data:
    name: vol_kafka2_data
  vol_zk1_data:
    name: vol_zk1_data
  vol_zk2_data:
    name: vol_zk2_data
  vol_zk3_data:
    name: vol_zk3_data
  vol_zk1_log:
    name: vol_zk1_log
  vol_zk2_log:
    name: vol_zk2_log
  vol_zk3_log:
    name: vol_zk3_log

services:

  zk1:
    image: zookeeper:3.7.0
    restart: unless-stopped
    container_name: zk1
    hostname: zk1
    networks:
      - kafka-net
    ports:
      - 2181:2181
    volumes:
      - vol_zk1_data:/mnt/zookeeper/data:rw
      - vol_zk1_log:/mnt/zookeeper/log:rw
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_DATA_DIR: /mnt/zookeeper/data
      ZOO_DATA_LOG_DIR: /mnt/zookeeper/log

  zk2:
    image: zookeeper:3.7.0
    restart: unless-stopped
    container_name: zk2
    hostname: zk2
    networks:
      - kafka-net
    ports:
      - 2182:2181
    volumes:
      - vol_zk2_data:/mnt/zookeeper/data:rw
      - vol_zk2_log:/mnt/zookeeper/log:rw
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_DATA_DIR: /mnt/zookeeper/data
      ZOO_DATA_LOG_DIR: /mnt/zookeeper/log

  zk3:
    image: zookeeper:3.7.0
    restart: unless-stopped
    container_name: zk3
    hostname: zk3
    networks:
      - kafka-net
    ports:
      - 2183:2181
    volumes:
      - vol_zk3_data:/mnt/zookeeper/data:rw
      - vol_zk3_log:/mnt/zookeeper/log:rw
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_DATA_DIR: /mnt/zookeeper/data
      ZOO_DATA_LOG_DIR: /mnt/zookeeper/log

  kafka0:
    image: docker.io/bitnami/kafka:3
    restart: unless-stopped
    container_name: kafka0
    hostname: kafka0
    networks:
      - kafka-net
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_CFG_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka0:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - vol_kafka0_data:/bitnami/kafka
    depends_on:
      - zk1
      - zk2
      - zk3

  kafka1:
    image: docker.io/bitnami/kafka:3
    restart: unless-stopped
    container_name: kafka1
    hostname: kafka1
    networks:
      - kafka-net
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - vol_kafka1_data:/bitnami/kafka
    depends_on:
      - zk1
      - zk2
      - zk3

  kafka2:
    image: docker.io/bitnami/kafka:3
    restart: unless-stopped
    container_name: kafka2
    hostname: kafka2
    networks:
      - kafka-net
    ports:
      - "9095:9095"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_CFG_BROKER_ID=2
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://localhost:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - vol_kafka2_data:/bitnami/kafka
    depends_on:
      - zk1
      - zk2
      - zk3

  karapace:
    image: ghcr.io/aiven/karapace:latest
    restart: unless-stopped
    container_name: karapace
    hostname: karapace
    command: ["/opt/karapace/start.sh", "registry"]
    networks:
      - kafka-net
    ports:
      - "8081:8081"
    environment:
      - KARAPACE_BOOTSTRAP_URI=kafka0:9092
      - KARAPACE_HOST=0.0.0.0
      - KARAPACE_REGISTRY_HOST=0.0.0.0
